version: '2'
services:
  frontend:
    ports:
      - "8080:8080"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend/src:/app/src"
    depends_on:
      - skeletor
  skeletor:
    ports:
      - "5000:5000"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/go/src/skeletor"
    depends_on:
      - postgres

  postgres:
    ports:
      - 5432:5432
    build:
      context: ./sql
      dockerfile: Dockerfile
